---
# create namespace
- name: Create a k8s namespace
  k8s:    
    state: present    
    definition:      
      apiVersion: v1      
      kind: Namespace      
      metadata:        
        name: "{{ namespace }}"