---

- name: Pause for 1 for sync
  ansible.builtin.pause:
    minutes: 1

- name: Get nodes data
  shell: sed -i '/gcp_node_worker_/d' inventory/gcp.yml && kubectl get nodes | grep "gke-{{ cluster_name }}-default-pool-" | awk '{print "  " "gcp_node_worker_" NR ":" " " $1}' >> inventory/gcp.yml

- name: Get nodes IP
  shell: sed -i '/ghost_ip/d' inventory/gcp.yml && kubectl describe nodes | grep ExternalIP | awk '{print "  " "ghost_ip:" " " $2}' | head -n 1 >> inventory/gcp.yml

- meta: refresh_inventory

- name: create folder /mnt/data
  shell: gcloud compute ssh --command "sudo mkdir -p /mnt/data" --zone "us-central1-a" "{{ gcp_node_worker_1 }}"  --project "{{ gcp_project }}" && \ 
         gcloud compute ssh --command "sudo mkdir -p /mnt/data" --zone "us-central1-a" "{{ gcp_node_worker_2 }}"  --project "{{ gcp_project }}"

