---
# Deployment for deploying ghost
- name: ghost deploy
  k8s:
    state: present
    definition:      
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ghost
        namespace: "{{ namespace }}"        
        labels:
          app: ghost
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: ghost
        template:
          metadata:
            labels:
              app: ghost
          spec:
            containers:
            - name: ghost
              image: ghost:4-alpine
              env:
              - name: database__connection__host
                value: mysql-service
              - name: database__connection__database
                value: swap
              - name: database__connection__user
                value: swapuser
              - name: database__connection__password
                value: "123456" # Use secret object in real usage
              - name: MIGRATE
                value: "true"
              ports:
              - containerPort: 2368

# Create Service for exposing ghost
- name: Create ghost Service
  k8s:
    state: present    
    definition:      
      apiVersion: v1
      kind: Service
      metadata:
        name: ghost-service
        namespace: "{{ namespace }}"        
        labels:
          app: ghost
          tier: app
      spec:
        type: NodePort # Makes the service accessible on a static port on each Node in the cluster.
        selector:
          app: ghost
        ports:
            # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
          - targetPort: 2368 # port that containers are listening on
            port: 2368 # port exposed internally in the cluster
            # Optional field
            # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
            nodePort: 30007 # a static port assigned on each the node
