---
# Playbook to create GKE cluster

- name: Create a GKE cluster
  hosts: localhost
  gather_facts: false
  roles:
    - { role: gke_cluster_create, tags: cluster_create }
    - { role: get-cluster-data, tags: cluster_data }
    - { role: create-namespace, tags: namespace }
    - { role: create-persistence, tags: persistence }
