---
# Playbook to deploy Ghost and its components
# TO DO
- name: deploy ghost
  hosts: localhost  
  gather_facts: false  
  environment:    
    GOOGLE_CREDENTIALS: "{{ gcp_cred_file }}"   
  roles:
    - { role: deploy-mysql, tags: mysql }
    - { role: deploy-ghost, tags: ghost }
    - { role: create-firewall-rule, tags: ["ghost", "firewall"] }