---
# Playbook to destroy GKE cluster

- name: Destroy GKE cluster
  hosts: localhost
  gather_facts: false
  roles:
    - delete-persistence
    - delete-namespace
    - delete-firewall-rule
    - gke_cluster_destroy