---
# Playbook to undeploy Ghost and its component
# TO DO
- name: undeploy ghost
  hosts: localhost
  gather_facts: false
  vars:
    delete_data: false
  environment:    
    GOOGLE_CREDENTIALS: "{{ gcp_cred_file }}"   
  roles:    
    - { role: undeploy-ghost, tags: ghost }
    - { role: delete-firewall-rule, tags: ["ghost", "firewall"] }
    - { role: undeploy-mysql, tags: mysql }
    - { role: delete-mysql-data, tags: ["mysql", "mysql_data"] }
