---
# Playbook to deploy Ghost and its components
# TO DO
- name: deploy ghost
  hosts: localhost  
  gather_facts: false  
  environment:    
    GOOGLE_CREDENTIALS: "{{ gcp_cred_file }}"   
  roles:
    - create-namespace
    - create-persistence-volumes
    - deploy-mysql
    - deploy-ghost