---
# Mysql Deployment
- name: Create k8s pod for mysql
  k8s:
    state: present    
    definition:      
      apiVersion: v1      
      kind: Pod      
      metadata:
        name: mysql
        namespace: "{{ namespace }}"        
        labels:
          app: mysql
          tier: database
      spec:
        containers:
        - name: mysql
          image: "{{ mysql_image }}"
          env: # The variables below could be set on a ConfigMap object
          - name: MYSQL_ALLOW_EMPTY_PASSWORD
            value: "true"
          - name: MYSQL_HOST
            value: mysql-service
          - name: MYSQL_DATABASE
            value: ghost_db
          - name: MYSQL_USER
            value: ghost_user
          - name: MYSQL_PASSWORD
            value: "123456" # Use Secret object in real usage
          ports:
          - containerPort: 3306
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
        volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
                claimName: mysql-pv-claim

- name: Create a MySQL Service
  k8s:
    state: present    
    definition:     
      apiVersion: v1
      kind: Service
      metadata:
        name: mysql-service # logical name of the service, which will also become the DNS name of the service when it is created.
        namespace: "{{ namespace }}"        
        labels:
          app: mysql
          tier: database
      spec:
        type: ClusterIP
        selector:
          app: mysql
        ports:
          - targetPort: 3306 # port that containers are listening on
            port: 3306 # port number exposed internally in the cluster


  # "database": {
  #   "client": "sqlite3",
  #   "connection": {
  #     "filename": "/var/lib/ghost/content/data/ghost.db"