---
# - name: Create a k8s namespace
#   k8s:    
#     state: present    
#     definition:      
#       apiVersion: v1      
#       kind: Namespace      
#       metadata:        
#         name: "{{ namespace }}" 
- name: Create k8s pod for nginx  
  k8s:    
    state: present    
    definition:      
      apiVersion: v1      
      kind: Pod      
      metadata:        
        name: "{{ app }}"        
        # namespace: "{{ namespace }}"        
        labels:          
          app: "{{ app }}"      
      spec:        
        containers:          
          - name: "{{ app }}"            
            image: "{{ image }}"            
            imagePullPolicy: Always
