---
# Delete Persistence volumes

- name: Delete a PV Claim
  k8s:
    state: absent
    definition:      
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mysql-pv-claim
        namespace: "{{ namespace }}"

- name: Delete a PV_WORKER1
  k8s:
    state: absent
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: pv001
        namespace: "{{ namespace }}"        

- name: Delete a PV_WORKER2
  k8s:
    state: absent
    definition:      
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: pv002
        namespace: "{{ namespace }}"        

- name: Delete a PV
  k8s:
    state: absent
    definition:      
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: local-storage
        namespace: "{{ namespace }}"          